name: Quarto Publish - Zh

on:
  workflow_dispatch:
  push:
    branches: master-zh

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
          ref: master-zh

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages-zh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
